### ISSUE TITLE
Email Digest Highlighting the Awesome Work of Other Employees

### ISSUE THREAD

**Issue by andrewudell** [hackmh/org#5]
Too often, people feel unappreciated at work. Let's build some sort of slackbot that collects anonymous thank yous and appreciations for other employees and sends them out weekly via an email digest to the whole team.

Example 1: Charlie, I can't tell you how much I appreciate you making coffee every morning. Such a pleasure to come into work and have a hot pot of coffee brewing.

Small or large, let's encourage everyone to be more thankful and let's make everyone feel more valued.

**Comment by mattjmcnaughton** [comment]
:+1: This is awesome. Here's the [repo](https://github.com/hackmh/shoutout).
