### ISSUE TITLE
Logo!

### ISSUE THREAD

**Issue by mattjmcnaughton** [hackmh/org#7]
@hackmh/contributors 

Looks like we're fortunate enough to have some options for logos! I know @grungerabbit is working on one and @andrewudell did an awesome one!

Thought we could discuss the options here.

**Comment by mattjmcnaughton** [comment]
Here's what @andrewudell submitted! :+1: 

![image](https://cloud.githubusercontent.com/assets/3269376/9155311/102294dc-3e82-11e5-9942-be309c5ad56c.png)

**Comment by grungerabbit** [comment]
Hey all, I've been unacceptably busy this last week and haven't had a chance to revisit hackMH work. I'm including a draft screenshot what I had worked on last week, so you can at least see the direction I was thinking. The colors and styling are all provisional, although I'm liking the center red version. The type is the main feature, based on Tyler Finck's [KORSQUE](http://www.tylerfinck.com/fonts/korsque/) typeface:

![screenshot 2015-08-19 07 46 50](https://cloud.githubusercontent.com/assets/1840745/9355378/c73f2114-4646-11e5-872d-98e15ad4ae13.png)

**Comment by mattjmcnaughton** [comment]
Looks great cheryl :+1: thanks so much for working on this!

lets take a couple of days and think about the options and then we can decide?

**Comment by andrewudell** [comment]
Woah, digging the style!

**Comment by mattjmcnaughton** [comment]
So I've been thinking about this - we've got two really cool options!

@andrewudell and @grungerabbit thoughts on collaborating together on a final design? (I can intro w/ email addresses if you need contact info). 

One thing I was thinking about:
- The usecase for this logo is mostly for github and mayble a favicon so perhaps it makes sense for it to be a square.

Thank you both for all your work!

**Comment by andrewudell** [comment]
Would love to!

**Comment by grungerabbit** [comment]
Hey everyone,

This is roughly what I'm thinking for the logo right now! I am still refining the shapes and am coloring with a paper version in order to come up with optimal color layouts. I am also considering assigning the colors randomly with code, which would be really cool and appropriate.

I will need to test this more thoroughly. Just wanted to show y'all what I'm working on!

![hackmh-brain-v1-01](https://cloud.githubusercontent.com/assets/1840745/9978296/3131c5c4-5ef5-11e5-9389-68540eb68b70.png)

**Comment by nancywong** [comment]
oooo i like

On Sat, Sep 19, 2015 at 5:38 PM, Cheryl Wu <notifications@github.com> wrote:

> Hey everyone,
>
> This is roughly what I'm thinking for the logo right now! I am still
> refining the shapes and am coloring with a paper version in order to come
> up with optimal color layouts. I am also considering assigning the colors
> randomly with code, which would be really cool and appropriate.
>
> I will need to test this more thoroughly. Just wanted to show y'all what
> I'm working on!
>
> [image: hackmh-brain-v1-01]
> <https://cloud.githubusercontent.com/assets/1840745/9978296/3131c5c4-5ef5-11e5-9389-68540eb68b70.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackmh/org/issues/7#issuecomment-141709639>.
>



-- 
Nancy Wong
Digital Media Design 2017
University of Pennsylvania · School of Engineering and Applied Science
www.nancywong.net · (423) 290-2358 · wongn@seas.upenn.edu

**Comment by andrewudell** [comment]
Nice work! Wanna sync up at the end of the week so I can update you on
Shoutout and we can talk about the logo some more?

Andrew

**Comment by grungerabbit** [comment]
Yes! I made a lot of progress yesterday with refinements and I'll try to finish up tonight so y'all can see :)

**Comment by andrewudell** [comment]
Sounds good.

**Comment by mattjmcnaughton** [comment]
nice work chery!

**Comment by andrewudell** [comment]
Not sure if this is helpful, but was playing around with the idea of a
neural network/trying to include nodes in the logo and came up with
this:[image:
Inline image 1]

**Comment by grungerabbit** [comment]
hey @andrewudell can you repost that image? it doesn't seem to have been included.

**Comment by andrewudell** [comment]
Weird...trying again now.

**Comment by mattjmcnaughton** [comment]
@andrewudell hmm that still doesn't seem to be working

**Comment by andrewudell** [comment]
![image](https://cloud.githubusercontent.com/assets/1693065/10081778/9813b680-62c4-11e5-923c-1ce62c9b4621.png)

**Comment by mattjmcnaughton** [comment]
@andrewudell Success!

I really like this!

**Comment by grungerabbit** [comment]
update - I promise I will finish and show y'all what I was working on by tonight. I've been super busy with tech@NYU and hackNY, but that's no excuse to hold this up.

@andrewudell the nodes idea is super interesting!

**Comment by andrewudell** [comment]
@grungerabbit <https://github.com/grungerabbit> Thanks! Looking forward to
see what you come up with.

**Comment by grungerabbit** [comment]
![hackmh-09](https://cloud.githubusercontent.com/assets/1840745/10357494/b770856c-6d50-11e5-9ffa-7371be1cb142.png)
![hackmh-08](https://cloud.githubusercontent.com/assets/1840745/10357491/b76bb17c-6d50-11e5-9b09-e54cb4f44030.png)
![hackmh-11](https://cloud.githubusercontent.com/assets/1840745/10357492/b76d9cc6-6d50-11e5-8c3c-1278444a5639.png)
![hackmh-12](https://cloud.githubusercontent.com/assets/1840745/10357495/b7711f5e-6d50-11e5-85aa-d9fe25d4a90a.png)
![hackmh-15](https://cloud.githubusercontent.com/assets/1840745/10357497/b7740976-6d50-11e5-9d01-27b5cf6298f9.png)
![hackmh-13](https://cloud.githubusercontent.com/assets/1840745/10357496/b7712a30-6d50-11e5-9c87-d49c7592f989.png)
![hackmh-14](https://cloud.githubusercontent.com/assets/1840745/10357493/b7706154-6d50-11e5-9b08-899f922cdf4e.png)
![hackmh-16](https://cloud.githubusercontent.com/assets/1840745/10357498/b775220c-6d50-11e5-9618-65246b930984.png)

**Comment by mattjmcnaughton** [comment]
Great work @grungerabbit!

Thoughts on @andrewudell and I and you all jumping on a call sometime this weekend and chatting?

**Comment by grungerabbit** [comment]
sunday sounds good!

**Comment by andrewudell** [comment]
I'm free all day on Sunday, so whatever works for you two works for me.

Andrew
